on: [push, pull_request]
name: win-ci
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ghc: ['8.10']
        cabal: ['3.2']
    name: Haskell GHC ${{ matrix.ghc }} sample
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal v2-build $CONFIG
        # there're bugs stop hacakge's zlib installation, which stop test from running
        #- if: matrix.cabal < '3'
        #  run: cabal v2-test
        #- if: matrix.cabal >= '3'
        #  run: cabal v2-test --test-show-details=direct
      - run: cabal v2-haddock
      - run: cabal v2-sdist
